### ISSUE TITLE
Implement test suite and configure testing environment

### ISSUE THREAD

**Issue by ghost** [zachtheclimber/mpv#15]
As indicated by the bugs found in the beta release, having a test suite for MPV is critical for moving forward. I am currently learning about Python unit testing, so hopefully this will be something I can work on in the near future. @benjpalmer, I know you have a vision for how this could work, so I'm happy to help you in any way I can. :-)

**Comment by benjpalmer** [comment]
Sweet! I will try to lay a small foundation and add a 'first-test'.

**Comment by benjpalmer** [comment]
Resolved by PR #18, I think we can close this issue.

**Comment by ghost** [comment]
I'd say so, and then some. :-)
