### ISSUE TITLE
Add test coverage for helpers

### ISSUE THREAD

**Issue by benjpalmer** [zachtheclimber/mpv#19]
I am proposing that we add test coverage for `app/helpers`. By adding test coverage we can be confident that when MPV is using these helper functions, the application will perform as expected.

What do you think @zachtheclimber? Do you mind if I take this on? Do you have any preference to code  structure/styling in regards to one large file vs many smaller files?

I'm wondering if it would help to logically separate some of the helper functions into their own files? For instance an example file could be `/helpers/db_connections.py` and that file could contain `db_connect()` and `db_close`. 

The reason I ask, is I am suspecting that by writing tests for some of these functions, there might be opportunity for some light refactoring, or abstracting logic out of some of the large helper functions into their own function or class.

Anyway, interested in hearing your thoughts! Happy to help in any way I can!

**Comment by ghost** [comment]
I think this would be a great addition, and I'd be happy for you to take it on. If there is logical grouping (such as you mentioned for `db_connections.py`) then I think splitting them out makes sense. Let's try not to end up with too many smaller files, however.

I'm going to be working on refactoring and cleaning up some of the existing code as well via the `clean-code` branch, so this might be a good opportunity for me to practice merging on Github. Any ideas for the best way for us to work on these things at the same time?

**Comment by benjpalmer** [comment]
Sweet! I will definitely try to keep the file count low, and focus only on logical separations.

I think for the most part we should have no issue working on these at the same time, I will only be cleaning things up in the helper functions. So my footprint of changes should be relatively small. If you were to do some refactoring and cleaning in any other place besides helpers, we would likely avoid any collisions and messy merge conflicts. If there are any merge conflicts I would bet we could resolve them quite easily.

**Comment by ghost** [comment]
I trust you to split them out in a way that makes sense. I was more just kind of typing out my thoughts on file divisions in general. I think the next application I build from scratch, I'll have a better feeling for how to divide things from the beginning. At least I knew to keep the graphing functions separate. :-)

I'll stay out of helpers until you are done. I have the main app cleaned up right now. I'll probably do the helpers once you are finished, just to make sure my comments aren't too verbose.

Thanks again for your help on this. I'm really learning a lot working with you. It's fun. :-)

**Comment by benjpalmer** [comment]
Thanks! I've been learning lots too! It's definitely fun to contribute to a climbing related project and collaborating with others is one of the best ways to learn.

**Comment by ghost** [comment]
This is resolved with PR [18](https://github.com/zachtheclimber/mpv/pull/20).
