### ISSUE TITLE
Implement test for email regex

### ISSUE THREAD

**Issue by benjpalmer** [zachtheclimber/mpv#21]
I am proposing that we add test coverage for this piece code found in `/app/__init__.py`:

```
# Input validation - Thanks to emailregex.com for the regex
regex = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
if not re.match(regex, email):
    e = "Please enter a valid email."
    return render_template("error.html", data=e)
```

This could maybe be extracted into it's own helper function. Tests should validate and invalidate many different types of email address patterns.

@zachtheclimber I think this would be a good way to dip your toes into writing some tests, would you want to take this on?

**Comment by ghost** [comment]
I think you're right on all accounts. I'd love to take this one on. I'm currently doing some clean up in the graphing functions (light refactoring, type hinting, comment clarification), then I'll move on to this.
