### ISSUE TITLE
Improve Handling of Application Errors

### ISSUE THREAD

**Issue by benjpalmer** [zachtheclimber/mpv#23]
After completing some refactoring of the helper functions in issue #19 , I thought there was a good opportunity to clearly define how we handle application errors. The expected responses can live in one location, and provide an organized and consistent structure throughout MPV. Then, when we add features such as grade conversions and other suggested enhancements, we already have the error handlers registered, defined and ready to be re-used.

Documentation and examples can be found here:
https://flask.palletsprojects.com/en/1.1.x/errorhandling/ 

@zachtheclimber, do you mind if I take this on?

**Comment by ghost** [comment]
If you're psyched to take this on, go for it! Happy to have MPV be a more robust app. I've been busy with other things lately, and haven't had time to work on it a ton, but I'm hoping to get back to doing more soon. Thanks for your continued contributions to these back end functions. :-)

**Comment by ghost** [comment]
Resolved by PR #24.
