### ISSUE TITLE
Obsolete README line?

### ISSUE THREAD

**Issue by ghost** [zachtheclimber/mpv#26]
While updating the README, I noticed that point 5 under installing may be obsolete:

> 5. To run the application on osx or Linux, set the `FLASK_APP` environment variable to `application` by running `export FLASK_APP=application`

With the refactoring of the app layout, I don't think this is required. In fact, when I try it on my Linux machine, it errors out. Just wanted to check with you, @benjpalmer, before I removed it, since I'm not familiar with how Flask functions in OSX. I think it is the same?

**Comment by benjpalmer** [comment]
Yeah, no problem, go ahead and remove. I think it was leftover from before the application file structure was refactored and I must have forgot to remove that line! Good catch!

**Comment by ghost** [comment]
Done!
