### ISSUE TITLE
General proposals.

### ISSUE THREAD

**Issue by benjpalmer** [zachtheclimber/mpv#4]
Hey @zachtheclimber,

My name is Ben and I am a fellow climber/developer, I had expressed interest in contributing on mountainproject and I always thought it would be fun to work on a climbing related project!!

I wanted to submit this parent issue and get your thoughts on a few ideas below. I think if we address some of the low hanging fruit and other small changes now, it will lay the foundation for adding additional features down the road. If you approve and want to implement anything, we could separate those issues into their own tickets.

I am proposing the following:

- **Add contributing guidelines**
If others want to jump in and contribute lets make sure we are all working as a team and know what is expected of one another.
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
Issue: #5 

- **Use a code formatting tool such as Black**
I have used black on other projects and it is awesome. There are other code formatting tools out there as well.
https://github.com/psf/black

- **Unit Testing**
Add unit tests using either unittest or pytest libraries.
Keep track of code coverage.

- **Update app environment config settings**
I think the use of "on" vs "off" in config.json could be replaced with boolean values.
Maybe some additional configuration optimizations
https://flask.palletsprojects.com/en/1.1.x/config/

- **Overall 'pythonic' refactoring** 
Small syntax changes throughout could be improved upon to be more 'pythonic'. I think through unit testing many of these will show themselves. For example:
```
    # Remove unneeded data fields
    # Delete in reverse order to make field posistions simpler
    remove = [12, 8, 7, 6, 4, 3, 2]
    for row in ticklist:
        for i in remove:
            del row[i]
```
could be refactored into its own helper function or instead use list comprehension or a generator expression.
` clean_ticklist = [[v for i,v in enumerate(row) if i not in remove] for row in ticklist]`

- **Add type hinting and function annotation**
For example:
```
def get_userid(email):
    """
    Get username/id using email via MountainProject.com API.
    (https://www.mountainproject.com/data)
    """
    # do some stuff
    return {"status": 0, "name": data['name'], "id": data['id']}
```
could be refactored to add hinting and annotation such as:
```
def get_userid(email: str) -> dict:
    """
    Get username/id using email via MountainProject.com API.
    (https://www.mountainproject.com/data)
    """
    # do some stuff
    return {"status": 0, "name": data['name'], "id": data['id']}
```

Thanks again for open sourcing your idea! This would be my first Flask project as a majority of my experience has been in a Django environment.

**Comment by ghost** [comment]
Hey @benjpalmer,

Thanks for your interest, enthusiasm, and ideas! I'd love to have your help with MPV. As you can tell by my code and this repo, I'm fairly new to both Python and Github. My last major programming project was routesetting feedback database/analysis software I wrote for a gym I worked at back in 2013. And it was written in PERL... With rusty skills from 2003. So, yeah, learning a lot of new things here, and psyched to do so. You might just have to bear with me a little bit though. :-)

- Contributing guidelines sound great. Perhaps we could collaborate on those together?

- Code formatting tool: Not familiar with Black or similar tools. I'll do some reading. If it is an industry standard kind of thing, I'm totally down.

- Unit testing: I'm learning about that now actually. MPV could definitely use them, as all the bugs have shown.

- Config settings: Didn't realize Flask had that class. Definitely looks like an easy fix/update.

- Pythonic Refactoring: List comprehensions scare me (haven't dove into them yet), but I understand it is better syntax. I'm happy to have the code changed for better style.

- Type Hinting / Function Annotation: This is another thing I've seen, but haven't learned about, although seeing it within my own code makes a lot more sense! As I said before, I'd be happy to adjust for better style.

Overall, I'm open to having MPV added to and modified to make it better. It's also nice to get to work with other people. :-) In my past life I was a science fiction author, so working collaboratively on big projects isn't new to me, just the content, platform, and standard procedures are.

Thanks again for your input and I look forward to having you on the project!

**Comment by benjpalmer** [comment]
Sweet! Glad your psyched and I think you will enjoy the simplicity and workflow of python!

A little bit about me, I am a former electrician turned self taught programmer and currently in my second year as a junior developer for an app company in Colorado (this is my first desk job and it's been great for my climbing). I am happy to help out in any way that I can.

Here is a great resource about the workflow of contributing to projects and what to expect from other contributors as you will be reviewing any pull requests that get submitted.
https://github.com/firstcontributions/first-contributions

Github and version control in general is awesome. But without attention and care, it can get messy really fast. There is tons out there about git workflow.

I am happy to create a separate issue for adding contribution guidelines and we can continue our discussion there about what things to include. Feel free to update any of the issues with appropriate tags as you see fit.
https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests

After the initial contribution guidelines have been layed out, we can get to work explicitly identifying some of the requirements for the other tasks at hand.

Looking forward to collaborating!

**Comment by ghost** [comment]
Closing since I think I've moved everything in here to its own issue.
